<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-01T19:22:47 IST" name="Suite" finished-at="2025-06-01T19:23:44 IST" duration-ms="56453">
    <groups>
    </groups>
    <test started-at="2025-06-01T19:22:47 IST" name="ChromeTest" finished-at="2025-06-01T19:23:04 IST" duration-ms="16510">
      <class name="qa.test.TestCase1">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:qa.test.TestCase1@24aed80c]" started-at="2025-06-01T19:22:47 IST" name="beforeTest" finished-at="2025-06-01T19:22:48 IST" duration-ms="381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeMethod(java.lang.String,org.testng.ITestResult)[pri:0, instance:qa.test.TestCase1@24aed80c]" started-at="2025-06-01T19:22:48 IST" name="beforeMethod" finished-at="2025-06-01T19:22:58 IST" duration-ms="9932" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=TestCase1.methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@24aed80c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@24aed80c]" started-at="2025-06-01T19:22:58 IST" name="methodForEnteringCredentials" finished-at="2025-06-01T19:23:03 IST" duration-ms="5065" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This test is intentionally failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This test is intentionally failed
at org.testng.Assert.fail(Assert.java:111)
at qa.test.TestCase1.methodForEnteringCredentials(TestCase1.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodForEnteringCredentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:qa.test.TestCase1@24aed80c]" started-at="2025-06-01T19:23:03 IST" name="afterMethod" finished-at="2025-06-01T19:23:03 IST" duration-ms="267" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=methodForEnteringCredentials status=FAILURE method=TestCase1.methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@24aed80c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:qa.test.TestCase1@24aed80c]" started-at="2025-06-01T19:23:03 IST" name="afterTest" finished-at="2025-06-01T19:23:04 IST" duration-ms="546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- qa.test.TestCase1 -->
    </test> <!-- ChromeTest -->
    <test started-at="2025-06-01T19:23:04 IST" name="FirefoxTest" finished-at="2025-06-01T19:23:27 IST" duration-ms="23548">
      <class name="qa.test.TestCase1">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:qa.test.TestCase1@6a2f6f80]" started-at="2025-06-01T19:23:04 IST" name="beforeTest" finished-at="2025-06-01T19:23:04 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeMethod(java.lang.String,org.testng.ITestResult)[pri:0, instance:qa.test.TestCase1@6a2f6f80]" started-at="2025-06-01T19:23:04 IST" name="beforeMethod" finished-at="2025-06-01T19:23:21 IST" duration-ms="16830" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=TestCase1.methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@6a2f6f80] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@6a2f6f80]" started-at="2025-06-01T19:23:21 IST" name="methodForEnteringCredentials" finished-at="2025-06-01T19:23:26 IST" duration-ms="4984" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This test is intentionally failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This test is intentionally failed
at org.testng.Assert.fail(Assert.java:111)
at qa.test.TestCase1.methodForEnteringCredentials(TestCase1.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodForEnteringCredentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:qa.test.TestCase1@6a2f6f80]" started-at="2025-06-01T19:23:26 IST" name="afterMethod" finished-at="2025-06-01T19:23:27 IST" duration-ms="1508" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=methodForEnteringCredentials status=FAILURE method=TestCase1.methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@6a2f6f80] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:qa.test.TestCase1@6a2f6f80]" started-at="2025-06-01T19:23:27 IST" name="afterTest" finished-at="2025-06-01T19:23:27 IST" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- qa.test.TestCase1 -->
    </test> <!-- FirefoxTest -->
    <test started-at="2025-06-01T19:23:27 IST" name="EdgeTest" finished-at="2025-06-01T19:23:44 IST" duration-ms="16335">
      <class name="qa.test.TestCase1">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:qa.test.TestCase1@399c4be1]" started-at="2025-06-01T19:23:27 IST" name="beforeTest" finished-at="2025-06-01T19:23:27 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeMethod(java.lang.String,org.testng.ITestResult)[pri:0, instance:qa.test.TestCase1@399c4be1]" started-at="2025-06-01T19:23:27 IST" name="beforeMethod" finished-at="2025-06-01T19:23:37 IST" duration-ms="9316" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=TestCase1.methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@399c4be1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@399c4be1]" started-at="2025-06-01T19:23:37 IST" name="methodForEnteringCredentials" finished-at="2025-06-01T19:23:42 IST" duration-ms="5265" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This test is intentionally failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This test is intentionally failed
at org.testng.Assert.fail(Assert.java:111)
at qa.test.TestCase1.methodForEnteringCredentials(TestCase1.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodForEnteringCredentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:qa.test.TestCase1@399c4be1]" started-at="2025-06-01T19:23:42 IST" name="afterMethod" finished-at="2025-06-01T19:23:44 IST" duration-ms="1394" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=methodForEnteringCredentials status=FAILURE method=TestCase1.methodForEnteringCredentials()[pri:0, instance:qa.test.TestCase1@399c4be1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:qa.test.TestCase1@399c4be1]" started-at="2025-06-01T19:23:44 IST" name="afterTest" finished-at="2025-06-01T19:23:44 IST" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- qa.test.TestCase1 -->
    </test> <!-- EdgeTest -->
  </suite> <!-- Suite -->
</testng-results>
